syntax = "proto3";

service Phonebook {
    rpc Lookup (LookupRequest) returns (LookupResponse);
    rpc AddEntry (AddEntryRequest) returns (AddEntryResponse);
    rpc GetKey (GetKeyRequest) returns (GetKeyResponse);
}

message LookupRequest {
    string name = 1; 
}

message LookupResponse {
    bool success = 1;
    string number = 2;
    string time = 3;
    bytes signature = 4;
}

message AddEntryRequest {
    string name = 1;
    string number = 2;
}

message AddEntryResponse {
    bool success = 1;
    string message = 3;
}

message GetKeyRequest {
}

message GetKeyResponse {
    string key = 1;
}